from django.test import TestCase
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
class Hosttest(TestCase):
    
    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)
        self.live_server_url = 'http://127.0.0.1:8000/'

    def tearDown(self):
        self.driver.quit()

    # def test_01_register_page(self):
    #     driver = self.driver
    #     driver.get(self.live_server_url)
    #     time.sleep(2)
    #     register_link = driver.find_element(By.CSS_SELECTOR, "#righ")
    #     register_link.click()
    #     time.sleep(2)
    #     username = driver.find_element(By.NAME, "username")
    #     email = driver.find_element(By.NAME, "email")
    #     password1 = driver.find_element(By.NAME, "password1")
    #     password2 = driver.find_element(By.NAME, "password2")
    #     username.send_keys("automated123")
    #     email.send_keys("automated@gmail.com")
    #     password1.send_keys("boringMATER@123")
    #     password2.send_keys("boringMATER@123")
    #     submit_button = driver.find_element(By.CSS_SELECTOR, "button[type='submit']")
    #     time.sleep(2)
    #     submit_button.click()
    #     time.sleep(5)

    def test_02_login_page(self):
        driver = self.driver
        driver.get(self.live_server_url)
        driver.maximize_window()
        time.sleep(2)
        theme=driver.find_element(By.CSS_SELECTOR,"summary.secondary")
        theme.click()
        time.sleep(1)
        light=driver.find_element(By.CSS_SELECTOR,"ul[role='listbox'] li:nth-child(2) a")
        light.click()
        time.sleep(2)
        theme.click()
        time.sleep(1)
        dark=driver.find_element(By.CSS_SELECTOR,"ul[role='listbox'] li:nth-child(3) a")
        dark.click()
        time.sleep(1)
        elem = driver.find_element(By.NAME, "username")
        elem.send_keys("dhunan")
        elem = driver.find_element(By.NAME, "password")
        elem.send_keys("asdASD@1234")
        submit_button = driver.find_element(By.CSS_SELECTOR, "button[type='submit']")
        submit_button.click()
        time.sleep(2)
        browse=driver.find_element(By.CSS_SELECTOR,"div.navbar-content > a:first-child")
        browse.click()
        time.sleep(1)
        driver.execute_script("window.scrollBy(0, 150);")
        time.sleep(1)
        view=driver.find_element(By.CSS_SELECTOR,"a[href*='/books/book/8/']")
        view.click()
        time.sleep(1)
        driver.execute_script("window.scrollBy(0, 600);")
        time.sleep(1)
        chaps=driver.find_element(By.CSS_SELECTOR,"button.chap-list")
        chaps.click()
        time.sleep(1)
        driver.execute_script("window.scrollBy(0, 300);")
        time.sleep(1)
        chap = driver.find_element(By.CSS_SELECTOR, 'a[href*="/books/8/chapter/Text/part0007.xhtml/"]')
        chap.click()
        time.sleep(1)
        driver.execute_script("window.scrollBy(0, 300);")
        time.sleep(1)
        driver.execute_script("window.scrollBy(0, -300);")
        time.sleep(1)
        options = driver.find_element(By.CSS_SELECTOR, 'button#options-button')
        options.click()
        options.click()
        time.sleep(1)
        select=driver.find_element(By.CSS_SELECTOR, 'select#font-style')
        select.click()
        time.sleep(1)
        option1=driver.find_element(By.CSS_SELECTOR, 'select#font-style option[value="calibri"]')
        option1.click()
        time.sleep(1)
        theme2=driver.find_element(By.CSS_SELECTOR, 'select#theme')
        theme2.click()
        time.sleep(1)
        option2=driver.find_element(By.CSS_SELECTOR, 'select#theme option[value="light"]')
        option2.click()
        time.sleep(1)
        theme2.click()
        increaseFont=driver.find_element(By.CSS_SELECTOR, 'span.adjust-button#font-size-increase')
        increaseFont.click()
        increaseFont.click()
        increaseFont.click()
        increaseFont.click()
        increaseFont.click()
        time.sleep(1)
        increasePad=driver.find_element(By.CSS_SELECTOR, 'span.adjust-button#content-padding-increase')
        increasePad.click()
        increasePad.click()
        increasePad.click()
        time.sleep(1)
        increaseLine=driver.find_element(By.CSS_SELECTOR, 'span.adjust-button#line-spacing-increase')
        increaseLine.click()
        increaseLine.click()
        increaseLine.click()
        time.sleep(1)
        options.click()
        title=driver.find_element(By.CSS_SELECTOR,"div.book-title a")
        title.click()
        time.sleep(1)
        driver.execute_script("window.scrollBy(0, 2000);")
        time.sleep(2)
        like = driver.find_element(By.CSS_SELECTOR,"div.like-button button.btn.btn-primary:first-child")
        like.click()
        time.sleep(2)
        driver.execute_script("window.scrollBy(0, -2000);")
        time.sleep(1)
        toLibrary = driver.find_element(By.CSS_SELECTOR,"div.breadcrumb a:nth-child(2)")
        toLibrary.click()
        time.sleep(1)
        search=driver.find_element(By.CSS_SELECTOR,"input#search-bar.search-bar")
        search.send_keys('monk')
        time.sleep(2)
        search.send_keys('')
        time.sleep(1)
        navbar_user = driver.find_element(By.CSS_SELECTOR,".navbar-user")
        action = ActionChains(driver)
        action.move_to_element(navbar_user).perform()
        profile = driver.find_element(By.CSS_SELECTOR, "div#dropdown-menu a[href='/user/profile']")
        profile.click()
        wait = WebDriverWait(driver, 10)
        time.sleep(1)
        bio = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "div.list-group a:nth-child(2)")))
        # bio=driver.find_element(By.CSS_SELECTOR, "div.list-group a:nth-child(2)")
        bio.click()
        time.sleep(1)
        contact=driver.find_element(By.CSS_SELECTOR, "div.list-group a:nth-child(3)")
        contact.click()
        time.sleep(1)
        time.sleep(1)
        wait = WebDriverWait(driver, 10)
        navbar_user = wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, "div.navbar-user.dropdown img.profile-image")))
        action = ActionChains(driver)
        action.move_to_element(navbar_user).perform()
        logout = driver.find_element(By.CSS_SELECTOR, "div#dropdown-menu a[href='/accounts/logout']")
        logout.click()
        time.sleep(1)

    # Add more test methods as needed

if __name__ == '__main__':
    import unittest
    unittest.main()