# Generated by Django 4.2.4 on 2024-02-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_readingprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingProgress',
        ),
    ]
