# Generated by Django 4.2.4 on 2023-08-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='cover_image',
        ),
    ]
