# Generated by Django 4.2.4 on 2023-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_books_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='PublicationDate',
            field=models.DateField(),
        ),
    ]
