# Generated by Django 4.2.4 on 2023-09-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name_plural': 'Languages'},
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='AuthorID',
            new_name='Author',
        ),
    ]
