# Generated by Django 4.2.4 on 2023-09-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_authors_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='AuthorID',
            new_name='Author',
        ),
    ]
