# Generated by Django 4.2.4 on 2023-09-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_rename_authorid_books_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('ASIN', 'ASIN'), ('ISBN', 'ISBN')], max_length=4)),
                ('identifier_value', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='identifiers',
            field=models.ManyToManyField(to='books.identifier'),
        ),
    ]
