# Generated by Django 4.2.4 on 2023-09-03 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_identifier_books_identifiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='identifiers',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='identifier_value',
        ),
        migrations.AddField(
            model_name='books',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.identifier'),
        ),
        migrations.AddField(
            model_name='books',
            name='identifier_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
