# Generated by Django 4.2.4 on 2023-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_books_identifier_books_identifier_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.RemoveField(
            model_name='books',
            name='ISBN',
        ),
        migrations.AddField(
            model_name='books',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='books.tag'),
        ),
    ]
