# Generated by Django 4.2.4 on 2023-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='character_rating',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='grammar_rating',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='story_rating',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='style_rating',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
