# Generated by Django 4.2.4 on 2023-09-10 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_review_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
