# Generated by Django 4.2.4 on 2023-09-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_review_likes_count_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
