# Generated by Django 4.2.4 on 2023-09-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_userlibrary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlibrary',
            options={'verbose_name_plural': 'User Libraries'},
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Categories',
            new_name='Genre',
        ),
    ]
