# Generated by Django 4.2.4 on 2023-09-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_alter_userlibrary_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Genre',
            new_name='Category',
        ),
    ]
