# Generated by Django 4.2.4 on 2023-09-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_socialmedialink_remove_authors_socialmedialinks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='number_of_works',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
