# Generated by Django 4.2.4 on 2023-09-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_authors_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='epub_file',
            field=models.FileField(blank=True, null=True, upload_to='book/epubs/'),
        ),
    ]
