# Generated by Django 4.2.4 on 2023-09-16 12:54

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_books_epub_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='epub_file',
        ),
        migrations.AddField(
            model_name='books',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book/pdfs/', validators=[books.models.validate_pdf_file]),
        ),
    ]
