# Generated by Django 4.2.4 on 2023-09-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_remove_books_epub_file_books_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book/pdfs/'),
        ),
    ]
