# Generated by Django 4.2.4 on 2023-09-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_alter_books_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='pdf_file',
        ),
    ]
