# Generated by Django 4.2.4 on 2023-09-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_books_epub_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover_image',
            field=models.ImageField(default=123, upload_to='book/book_cover'),
            preserve_default=False,
        ),
    ]
