# Generated by Django 4.2.4 on 2023-09-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_shoppingcart_purchasehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
