# Generated by Django 4.2.4 on 2024-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0042_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(null=True),
        ),
    ]
