# Generated by Django 4.2.4 on 2024-03-04 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0044_alter_vote_vote_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='books.userlibrary')),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.folder')),
            ],
            options={
                'unique_together': {('folder', 'book')},
            },
        ),
    ]
