# Generated by Django 4.2.4 on 2024-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0046_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='isOriginal',
            field=models.BooleanField(default=False),
        ),
    ]
