# Generated by Django 4.2.4 on 2024-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0051_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='addressed',
            field=models.BooleanField(default=False),
        ),
    ]
