# Generated by Django 4.2.4 on 2023-08-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='expires_at',
        ),
    ]
