# Generated by Django 4.2.4 on 2023-08-16 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_otpmodel_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
