# Generated by Django 4.2.4 on 2023-08-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_authors_languages_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='AuthorID',
        ),
        migrations.RemoveField(
            model_name='books',
            name='LanguageID',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
