# Generated by Django 4.2.4 on 2023-09-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_purchasehistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'verbose_name_plural': 'Purchase Histories'},
        ),
    ]
