# Generated by Django 4.2.4 on 2023-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_content',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
