# Generated by Django 4.2.4 on 2023-10-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_items'),
        ('user', '0013_notification_extra_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_history', to='payment.order'),
        ),
    ]
