# Generated by Django 4.2.4 on 2024-02-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
